// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRPiefOu1fZ4-ute5lf_8dm5eLT2mcDL8',
    appId: '1:38458733937:web:d0bcc1bf887de1aa3a32d0',
    messagingSenderId: '38458733937',
    projectId: 'quickbite-d7727',
    authDomain: 'quickbite-d7727.firebaseapp.com',
    storageBucket: 'quickbite-d7727.firebasestorage.app',
    measurementId: 'G-H2ZRBV2M02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4vV5k4S6J3uZARBwPXbsUuiom0PHpp0A',
    appId: '1:38458733937:android:94ff44a04fbf25843a32d0',
    messagingSenderId: '38458733937',
    projectId: 'quickbite-d7727',
    storageBucket: 'quickbite-d7727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxoHJNfnY2JKKaHJOXDkkMACMsCbrJGRA',
    appId: '1:38458733937:ios:35588920887d72263a32d0',
    messagingSenderId: '38458733937',
    projectId: 'quickbite-d7727',
    storageBucket: 'quickbite-d7727.firebasestorage.app',
    iosBundleId: 'com.example.quickbiteMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxoHJNfnY2JKKaHJOXDkkMACMsCbrJGRA',
    appId: '1:38458733937:ios:35588920887d72263a32d0',
    messagingSenderId: '38458733937',
    projectId: 'quickbite-d7727',
    storageBucket: 'quickbite-d7727.firebasestorage.app',
    iosBundleId: 'com.example.quickbiteMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRPiefOu1fZ4-ute5lf_8dm5eLT2mcDL8',
    appId: '1:38458733937:web:2b97c27c8240a6e13a32d0',
    messagingSenderId: '38458733937',
    projectId: 'quickbite-d7727',
    authDomain: 'quickbite-d7727.firebaseapp.com',
    storageBucket: 'quickbite-d7727.firebasestorage.app',
    measurementId: 'G-3CYXMGVYE7',
  );
}
